# Generated by Django 4.1 on 2024-05-26 00:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 26, 0, 21, 14, 274580, tzinfo=datetime.timezone.utc)),
        ),
    ]
