# Generated by Django 4.1 on 2024-05-26 00:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_alter_appointment_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='address',
            new_name='street',
        ),
        migrations.AddField(
            model_name='appointment',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='state',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='zip_code',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 26, 0, 35, 48, 223217, tzinfo=datetime.timezone.utc)),
        ),
    ]
