# Generated by Django 4.1 on 2024-05-26 01:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_rename_address_appointment_street_appointment_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 26, 1, 25, 52, 58716, tzinfo=datetime.timezone.utc)),
        ),
    ]
