# Generated by Django 4.1 on 2024-05-26 01:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_alter_appointment_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 26, 1, 31, 16, 948687, tzinfo=datetime.timezone.utc)),
        ),
    ]
