# Generated by Django 4.1 on 2024-05-26 18:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0006_alter_appointment_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 26, 18, 50, 27, 318578, tzinfo=datetime.timezone.utc)),
        ),
    ]
