# Generated by Django 4.1 on 2024-05-25 23:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('review_text', models.TextField()),
                ('create_date', models.DateTimeField(default=datetime.datetime(2024, 5, 25, 23, 43, 13, 985824, tzinfo=datetime.timezone.utc))),
                ('approved', models.BooleanField(default=False)),
            ],
        ),
    ]
