# Generated by Django 4.1 on 2024-05-26 00:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_remove_review_create_date_review_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 26, 0, 20, 6, 754950, tzinfo=datetime.timezone.utc)),
        ),
    ]
