# Generated by Django 4.1 on 2024-05-26 01:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_alter_review_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 26, 1, 25, 52, 57696, tzinfo=datetime.timezone.utc)),
        ),
    ]
