# Generated by Django 4.1 on 2024-05-26 18:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_rename_customer_name_review_name_review_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 26, 18, 50, 27, 317557, tzinfo=datetime.timezone.utc)),
        ),
    ]
