# Generated by Django 4.1 on 2024-06-06 20:12

from django.db import migrations, models
import uuid

class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_alter_review_created_at'),
    ]

    operations = [
    ]
