# Generated by Django 4.1 on 2024-06-06 20:29

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_fill_tokens'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
            preserve_default = False,
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 6, 20, 29, 16, 434211, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='review',
            name='phone_number',
            field=models.CharField(max_length=15, null=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_text',
            field=models.TextField(verbose_name='Review'),
        ),
        migrations.AlterField(
            model_name='review',
            name='state',
            field=models.CharField(default='NY', max_length=2),
        ),
        migrations.AlterField(
            model_name='review',
            name='zip_code',
            field=models.CharField(max_length=10, null=True, verbose_name='Zip Code'),
        ),
    ]
